export const state = {
  isRunning: false,
  isPaused: false,
  stopRequested: false,
  promptList: [],
  failedPromptsList: [],
  taskList: [],
  masterTaskList: [],
  masterQueue: [],
  currentJobIndex: 0,
  imageFileList: [],
  imagePromptPairs: [],
  framePairsMeta: null,
  currentMode: "text-to-video",
  currentIndex: 0,
  flowTabId: null,
  currentProjectId: null,
  zoomResetTimerId: null,
  downloadInterval: null,
  scanIntervalMs: 2000,
  hotScanIntervalMs: 500,
  generationScanTimeoutMs: 8 * 60 * 1000,
  finalScanTimerId: null,
  downloadedVideoUrls: new Set(),
  activeDownloads: new Map(),
  scanInFlight: false,
  videoScanAttemptCount: 0,
  lastVideoScanAt: 0,
  lastVideoScanDiagnostics: null,
  lastDownloadStatusUiAt: 0,
  lastEmptyVideoScanLogAt: 0,
  newlyDownloadedCount: 0,
  selectors: {},
  currentLang: "vi",
  activeRunMode: null,
  MAX_RETRIES: 3,
  nextProjectCounter: 1,
};
